

path: /Volumes/Mac OS - Data/Projects/object_detection/airpods
train: train/images
val: valid/images
test: test/images
batch_size: 8
epochs: 200
lr0: 0.001
scheduler: cosine
augment: True
#img_size: 416

nc: 1
names: ['Airpods']



#names:
#  0: airpod





